"""empty message

Revision ID: 40aabbf5f165
Revises: aa2ee2a5ac93
Create Date: 2018-01-02 21:14:12.484595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40aabbf5f165'
down_revision = 'aa2ee2a5ac93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alertTable', sa.Column('deviceID', sa.String(length=10), nullable=True))
    op.drop_constraint(u'alerttable_ibfk_1', 'alertTable', type_='foreignkey')
    op.create_foreign_key(None, 'alertTable', 'devicesTable', ['deviceID'], ['deviceID'])
    op.drop_column('alertTable', 'sourceID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alertTable', sa.Column('sourceID', mysql.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'alertTable', type_='foreignkey')
    op.create_foreign_key(u'alerttable_ibfk_1', 'alertTable', 'devicesTable', ['sourceID'], ['deviceID'])
    op.drop_column('alertTable', 'deviceID')
    # ### end Alembic commands ###
