"""empty message

Revision ID: 5fc79c9963aa
Revises: e57e0e5f214d
Create Date: 2017-12-26 14:56:42.821499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc79c9963aa'
down_revision = 'e57e0e5f214d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DHT11Data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('hum_value', sa.Float(), nullable=True),
    sa.Column('tem_value', sa.Float(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DHT11Data')
    # ### end Alembic commands ###
