"""empty message

Revision ID: 844f63852fc2
Revises: 
Create Date: 2018-01-04 14:13:09.011378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844f63852fc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devicesTable',
    sa.Column('ID', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('changeTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('logTable',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('log', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('alertTable',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('ID', sa.String(length=10), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ID'], ['devicesTable.ID'], ),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('data1001Table',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('ID', sa.String(length=10), nullable=True),
    sa.Column('temIn', sa.String(length=10), nullable=True),
    sa.Column('humIn', sa.String(length=10), nullable=True),
    sa.Column('temOut', sa.String(length=10), nullable=True),
    sa.Column('humOut', sa.String(length=10), nullable=True),
    sa.Column('temSoil1', sa.String(length=10), nullable=True),
    sa.Column('humSoil1', sa.String(length=10), nullable=True),
    sa.Column('temSoil2', sa.String(length=10), nullable=True),
    sa.Column('humSoil2', sa.String(length=10), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ID'], ['devicesTable.ID'], ),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('notificationTable',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('SID', sa.String(length=10), nullable=True),
    sa.Column('TID', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['SID'], ['devicesTable.ID'], ),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('statusTable',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('ID', sa.String(length=10), nullable=True),
    sa.Column('changeTime', sa.DateTime(), nullable=True),
    sa.Column('col1', sa.Text(), nullable=True),
    sa.Column('col2', sa.Text(), nullable=True),
    sa.Column('col3', sa.Text(), nullable=True),
    sa.Column('col4', sa.Text(), nullable=True),
    sa.Column('col5', sa.Text(), nullable=True),
    sa.Column('col6', sa.Text(), nullable=True),
    sa.Column('col7', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ID'], ['devicesTable.ID'], ),
    sa.PrimaryKeyConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statusTable')
    op.drop_table('notificationTable')
    op.drop_table('data1001Table')
    op.drop_table('alertTable')
    op.drop_table('logTable')
    op.drop_table('devicesTable')
    # ### end Alembic commands ###
