"""empty message

Revision ID: aa2ee2a5ac93
Revises: 
Create Date: 2018-01-02 21:13:49.415098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2ee2a5ac93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devicesTable',
    sa.Column('deviceID', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('changeTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('deviceID')
    )
    op.create_table('logTable',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('log', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('alertTable',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('sourceID', sa.String(length=10), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sourceID'], ['devicesTable.deviceID'], ),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('data1001Table',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('deviceID', sa.String(length=10), nullable=True),
    sa.Column('temValue', sa.Float(), nullable=True),
    sa.Column('humValue', sa.Float(), nullable=True),
    sa.Column('windCtrl', sa.Integer(), nullable=True),
    sa.Column('temCtrl', sa.Float(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deviceID'], ['devicesTable.deviceID'], ),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('notificationTable',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('sourceID', sa.String(length=10), nullable=True),
    sa.Column('targetID', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sourceID'], ['devicesTable.deviceID'], ),
    sa.PrimaryKeyConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificationTable')
    op.drop_table('data1001Table')
    op.drop_table('alertTable')
    op.drop_table('logTable')
    op.drop_table('devicesTable')
    # ### end Alembic commands ###
