"""empty message

Revision ID: af8b9f0ba258
Revises: 
Create Date: 2018-03-29 15:08:26.995565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8b9f0ba258'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devicesTable',
    sa.Column('ID', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('changeTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('greenHouseImages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imgData', sa.BLOB(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logTable',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('log', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertTable',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('ID', sa.String(length=10), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ID'], ['devicesTable.ID'], ),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('data1001Table',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('ID', sa.String(length=10), nullable=True),
    sa.Column('temIn', sa.String(length=10), nullable=True),
    sa.Column('humIn', sa.String(length=10), nullable=True),
    sa.Column('temOut', sa.String(length=10), nullable=True),
    sa.Column('humOut', sa.String(length=10), nullable=True),
    sa.Column('temSoil1', sa.String(length=10), nullable=True),
    sa.Column('humSoil1', sa.String(length=10), nullable=True),
    sa.Column('temSoil2', sa.String(length=10), nullable=True),
    sa.Column('humSoil2', sa.String(length=10), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ID'], ['devicesTable.ID'], ),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('notificationTable',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('SID', sa.String(length=10), nullable=True),
    sa.Column('TID', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['SID'], ['devicesTable.ID'], ),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('statusTable',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('ID', sa.String(length=10), nullable=True),
    sa.Column('changeTime', sa.DateTime(), nullable=True),
    sa.Column('col1', sa.String(length=50), nullable=True),
    sa.Column('col2', sa.String(length=50), nullable=True),
    sa.Column('col3', sa.String(length=50), nullable=True),
    sa.Column('col4', sa.String(length=50), nullable=True),
    sa.Column('col5', sa.String(length=50), nullable=True),
    sa.Column('col6', sa.String(length=50), nullable=True),
    sa.Column('col7', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ID'], ['devicesTable.ID'], ),
    sa.PrimaryKeyConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statusTable')
    op.drop_table('notificationTable')
    op.drop_table('data1001Table')
    op.drop_table('alertTable')
    op.drop_table('users')
    op.drop_table('logTable')
    op.drop_table('greenHouseImages')
    op.drop_table('devicesTable')
    # ### end Alembic commands ###
