"""empty message

Revision ID: b71e2b24fb9c
Revises: 844f63852fc2
Create Date: 2018-01-07 14:09:18.878559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71e2b24fb9c'
down_revision = '844f63852fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greenHouseImages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imgData', sa.LargeBinary(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('greenHouseImages')
    # ### end Alembic commands ###
