"""empty message

Revision ID: e57e0e5f214d
Revises: 234845af1fa1
Create Date: 2017-12-26 14:54:03.843773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57e0e5f214d'
down_revision = '234845af1fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DHT11Data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('hum_value', sa.Float(), nullable=True),
    sa.Column('tem_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DHT11Data')
    # ### end Alembic commands ###
